version: '3.1'
services:
#POSTGRES
  db:
    build: ./db
    #restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
#NODE
  node:
    build: .
    #restart: always
    ports:
     - "3323:3323"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - .:/app/api