version: '3.1'
services:
  node:
    build: .
    ports:
     - "3000:3000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - .:/app/api
    networks:
      - mysql-compose-network
  db:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3318:3306
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
