// Extenção - REST Client

GET http://localhost:3333/users
Content-Type: application/json
###

POST http://localhost:3333/auth
Content-Type: application/json

{
    "name":"rick",
    "password":"321321321"
}